dependencies:
  controllers:
    SecurityController: App\controller\SecurityController
    CompteController: App\controller\CompteController
    TransactionController: App\controller\TransactionController
  services:
    CompteService: App\service\CompteService
    SecurityService: App\service\SecurityService
    TransactionService: App\service\TransactionService
  repository:
    UtilisateurRepository: App\repository\UtilisateurRepository
    CompteRepository: App\repository\CompteRepository
    TransactionRepository: App\repository\TransactionRepository
  core:
    Database: App\core\Database
    PDO: PDO
    Session: App\core\Session
  middlewares:
    auth: App\core\middlewares\Auth